project_name: 'galax-app'

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - goos:
    - linux
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc